apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-eso
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-cluster-scope
    kind: ClusterSecretStore
  target:
    name: test-secret
    creationPolicy: Owner
  data:
  - secretKey: USER
    remoteRef:
      key: k8s/secret_data
      property: user
  - secretKey: PASSWORD
    remoteRef:
      key: k8s/secret_data
      property: password
